version: "3"

services:
  app:
    build: .
    ports:
      - 8000
    restart: unless-stopped
    networks:
      - web

  nginx:
      restart: unless-stopped
      build: ./nginx
      container_name: nginx
      ports:
        - 80:80
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

      depends_on:
        - app
      networks:
       - web
  

networks:
  web:
    driver: bridge